### ISSUE TITLE
jquery.selectric.js [sm]:807 Uncaught TypeError: Cannot read property 'offsetTop' of undefined

### ISSUE THREAD

**Issue by radiocity** [lcdsantos/jQuery-Selectric#153]
Dev console information:
```
jquery.selectric.js [sm]:807 Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at r.detectItemVisibility (http://localhost:8000/assets/js/jquery.selectric.js:17:9751)
    at r.open (http://localhost:8000/assets/js/jquery.selectric.js:17:10892)
    at HTMLInputElement.<anonymous> (http://localhost:8000/assets/js/jquery.selectric.js:17:7497)
    at HTMLInputElement.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js:3:7519)
    at HTMLInputElement.r.handle (https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js:3:5600)
    at Object.trigger (https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js:4:4540)
    at Object.simulate (https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js:4:4958)
    at HTMLDocument.c (https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js:4:5720)
    at HTMLInputElement.trigger (https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js:3:9414)
    at Object.trigger (https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js:4:4200)detectItem
Visibility @ jquery.selectric.js [sm]:807
open @ jquery.selectric.js [sm]:884
(anonymous function) @ jquery.selectric.js [sm]:628
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
trigger @ jquery.min.js:4
simulate @ jquery.min.js:4
c @ jquery.min.js:4
trigger @ jquery.min.js:3
trigger @ jquery.min.js:4
(anonymous function) @ jquery.min.js:4
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:4
n.fn.(anonymous function) @ jquery.min.js:4
(anonymous function) @ jquery.selectric.js [sm]:613
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
```
Code string: 
```js
 var liTop = _this.$li[index].offsetTop;
```
Commit-ish version: 2cbffd9203ee7369054fb7640a5c1958661af55a

**Comment by radiocity** [comment]
Sorry. Select without options.
